version: '3.8'
services:
  PROJECTNAME_mysqldb:
    image: mysql:5.7
    container_name: PROJECTNAME_mysqldb
    restart: always
    env_file:
      - ./.env.dev
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - PROJECTNAME_mysql-db-data:/var/lib/mysql
volumes:
  PROJECTNAME_mysql-db-data:
